name = "Aeron"
uuid = "b850ffb1-6704-484e-996b-4710e2f097f0"
authors = ["Darryl Gamroth <dgamroth@rubus.ca>"]
version = "0.18.14"

[deps]
Aeron_jll = "d964258c-d1ad-568a-aca9-3ef511f5bffd"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
StringViews = "354b36f9-a18e-4713-926e-db85100087ba"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"

[compat]
Aeron_jll = "1.48"
CEnum = "0.4 - 1"
EnumX = "1.0"
StringViews = "1.3"
UUIDs = "1"
UnsafeArrays = "1.0"
julia = "1.10"

[extras]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Downloads", "Sockets", "Test"]
